import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
import { createSupabaseClient } from "@safer-streets/db";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

function getSupabase() {
  return createSupabaseClient();
}

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext: ({ context }) => ({
    ...context,
    getSupabase,
  }),
});
